@startuml

class Bird {
    +String name
    +String color
    +{abstract} speak(): void
    +fly(): void
}

class Pigeon{
    +speak(): void
    +eatPizza(): void
}
Bird <|-- Pigeon

class Penguin{
    +speak(): void
    +fly(): void
}
Bird <|-- Penguin

@enduml